name: Update Nifty Data

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 2 PM UTC (after market close)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for pushing to the repo
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas
          
      - name: Create data directory
        run: mkdir -p data
          
      - name: Update data
        run: |
          python update_data.py
          
      - name: Verify data file
        run: |
          ls -la data/
          cat data/nifty_returns.json

      # Commit data updates first
      - name: Commit data updates
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/nifty_returns.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Nifty returns data" && git push)

      # Then handle the build and deployment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Node dependencies
        run: |
          npm ci
          npm install tailwindcss-animate @tailwindcss/typography class-variance-authority clsx tailwind-merge lucide-react
          
      - name: Build project
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # Keep gh-pages branch clean
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
